-- USGC Color Schemes for Neovim
-- Ported from https://github.com/usgraphics/usgc-themes
-- All credit to U.S. Graphics Company
--
-- Standard USGC color palette
local M = {}

M.palette = {
  black = '#000000',
  white = '#FFFFFF',
  fl_red = '#FF0000',
  fl_green = '#00FF00',
  fl_blue = '#0000FF',
  fl_cyan = '#00FFFF',
  fl_magenta = '#FF00FF',
  fl_yellow = '#FFFF00',
  fl_orange = '#FF6600',
  maroon = '#660000',
  green = '#00A645',
  blue = '#000066',
  cyan = '#006666',
  magenta = '#660066',
  yellow = '#FFBF00',
  olive = '#666600',
  gray = '#999999',
}

-- Apply a colorscheme
-- @param name string
-- @param groups table<string, table>
-- @param terminal table<number, string>
function M.apply(name, groups, terminal)
  vim.cmd('highlight clear')
  vim.g.colors_name = name

  for group_name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group_name, spec)
  end

  for i = 0, 15 do
    vim.g['terminal_color_' .. i] = terminal[i]
  end
end

-- Generate highlight groups for a theme variant
-- @param opts table with:
--   bg, fg, accent, caret
--   selection_bg, selection_fg (for Visual, Search)
--   cursorline_bg (for CursorLine - subtle)
--   popup_bg, popup_sel_bg, popup_sel_fg (for Pmenu, floats)
--   gutter_fg, gutter_highlight
function M.make_groups(opts)
  local p = M.palette

  return {
    -- Treesitter
    ['@attribute'] = { link = 'Macro' },
    ['@attribute.builtin'] = { link = 'Special' },
    ['@boolean'] = { link = 'Boolean' },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { link = 'DiagnosticError' },
    ['@comment.note'] = { link = 'DiagnosticInfo' },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.warning'] = { link = 'DiagnosticWarn' },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { link = 'Special' },
    ['@constructor'] = { link = 'Special' },
    ['@diff'] = {},
    ['@diff.delta'] = { link = 'Changed' },
    ['@diff.minus'] = { link = 'Removed' },
    ['@diff.plus'] = { link = 'Added' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { link = 'Special' },
    ['@keyword'] = { link = 'Keyword' },
    ['@label'] = { link = 'Label' },
    ['@lsp'] = {},
    ['@lsp.mod.deprecated'] = { link = 'DiagnosticDeprecated' },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.comment'] = { link = '@comment' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.event'] = { link = '@type' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.keyword'] = { link = '@keyword' },
    ['@lsp.type.macro'] = { link = '@constant.macro' },
    ['@lsp.type.method'] = { link = '@function.method' },
    ['@lsp.type.modifier'] = { link = '@type.qualifier' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.number'] = { link = '@number' },
    ['@lsp.type.operator'] = { link = '@operator' },
    ['@lsp.type.parameter'] = { link = '@variable.parameter' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.regexp'] = { link = '@string.regexp' },
    ['@lsp.type.string'] = { link = '@string' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type.definition' },
    ['@lsp.type.variable'] = { link = '@variable' },
    ['@markup'] = { link = 'Special' },
    ['@markup.heading'] = { link = 'Title' },
    ['@markup.italic'] = { italic = true },
    ['@markup.link'] = { link = 'Underlined' },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.underline'] = { underline = true },
    ['@module'] = { link = 'Structure' },
    ['@module.builtin'] = { link = 'Special' },
    ['@number'] = { link = 'Number' },
    ['@number.float'] = { link = 'Float' },
    ['@operator'] = { link = 'Operator' },
    ['@property'] = { link = 'Identifier' },
    ['@punctuation'] = { link = 'Delimiter' },
    ['@punctuation.special'] = { link = 'Special' },
    ['@spell'] = {},
    ['@string'] = { link = 'String' },
    ['@string.escape'] = { link = '@string.special' },
    ['@string.regexp'] = { link = '@string.special' },
    ['@string.special'] = { link = 'SpecialChar' },
    ['@string.special.url'] = { link = 'Underlined' },
    ['@tag'] = { link = 'Tag' },
    ['@tag.builtin'] = { link = 'Special' },
    ['@text'] = {},
    ['@text.diff.add'] = { link = 'DiffAdd' },
    ['@text.diff.delete'] = { link = 'DiffDelete' },
    ['@text.note'] = { link = 'Todo' },
    ['@text.todo'] = { link = 'Todo' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { link = 'Special' },
    ['@variable'] = { fg = opts.fg },
    ['@variable.builtin'] = { link = 'Special' },
    ['@variable.parameter.builtin'] = { link = 'Special' },

    -- Standard highlight groups
    Bold = { bold = true },
    Boolean = { link = 'Constant' },
    Character = { link = 'Constant' },
    ColorColumn = { bg = opts.cursorline_bg },
    Comment = { fg = p.gray },
    ComplMatchIns = {},
    Conceal = {},
    Conditional = { link = 'Statement' },
    Constant = { fg = opts.fg },
    Cursor = { fg = opts.bg, bg = opts.caret },
    CursorColumn = { bg = opts.cursorline_bg },
    CursorIM = {},
    CursorLine = { bg = opts.cursorline_bg },
    CursorLineFold = { link = 'FoldColumn' },
    CursorLineNr = { fg = opts.gutter_highlight },
    CursorLineSign = { link = 'SignColumn' },
    Debug = { link = 'Special' },
    Define = { link = 'PreProc' },
    Delimiter = { fg = opts.fg },
    DiagnosticError = { fg = p.fl_red },
    DiagnosticFloatingError = { link = 'DiagnosticError' },
    DiagnosticFloatingHint = { link = 'DiagnosticHint' },
    DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
    DiagnosticFloatingOk = { link = 'DiagnosticOk' },
    DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
    DiagnosticHint = { fg = p.gray },
    DiagnosticInfo = { fg = p.fl_cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticSignError = { link = 'DiagnosticError' },
    DiagnosticSignHint = { link = 'DiagnosticHint' },
    DiagnosticSignInfo = { link = 'DiagnosticInfo' },
    DiagnosticSignOk = { link = 'DiagnosticOk' },
    DiagnosticSignWarn = { link = 'DiagnosticWarn' },
    DiagnosticUnnecessary = { link = 'Comment' },
    DiagnosticVirtualLinesError = { link = 'DiagnosticError' },
    DiagnosticVirtualLinesHint = { link = 'DiagnosticHint' },
    DiagnosticVirtualLinesInfo = { link = 'DiagnosticInfo' },
    DiagnosticVirtualLinesOk = { link = 'DiagnosticOk' },
    DiagnosticVirtualLinesWarn = { link = 'DiagnosticWarn' },
    DiagnosticVirtualTextError = { link = 'DiagnosticError' },
    DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
    DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
    DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
    DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
    DiagnosticWarn = { fg = p.fl_orange },
    Added = { fg = p.green },
    Changed = { fg = p.fl_cyan },
    Removed = { fg = p.fl_red },
    DiffAdd = { fg = p.black, bg = p.green },
    DiffChange = { fg = opts.fg, bg = opts.cursorline_bg },
    DiffDelete = { fg = p.white, bg = p.maroon },
    DiffText = { fg = p.black, bg = opts.accent, bold = true },
    Directory = { fg = opts.accent },
    EndOfBuffer = { link = 'NonText' },
    Error = { fg = opts.bg, bg = p.fl_red, bold = true },
    ErrorMsg = { fg = p.fl_red },
    Exception = { link = 'Statement' },
    Float = { link = 'Number' },
    FloatBorder = { fg = opts.accent, bg = opts.popup_bg },
    FloatFooter = { link = 'FloatTitle' },
    FloatTitle = { link = 'Title' },
    FoldColumn = { fg = p.gray },
    Folded = { fg = p.gray, bg = opts.cursorline_bg },
    Function = { fg = opts.fg },
    Identifier = { fg = opts.fg },
    Ignore = { link = 'Normal' },
    IncSearch = { fg = opts.bg, bg = opts.accent, bold = true },
    Include = { link = 'PreProc' },
    Italic = { italic = true },
    Keyword = { link = 'Statement' },
    Label = { link = 'Statement' },
    LineNr = { fg = opts.gutter_fg },
    LineNrAbove = { link = 'LineNr' },
    LineNrBelow = { link = 'LineNr' },
    LspCodeLens = { link = 'NonText' },
    LspCodeLensSeparator = { link = 'LspCodeLens' },
    LspInlayHint = { link = 'NonText' },
    LspReferenceRead = { link = 'LspReferenceText' },
    LspReferenceTarget = { link = 'LspReferenceText' },
    LspReferenceText = { bg = opts.cursorline_bg },
    LspReferenceWrite = { link = 'LspReferenceText' },
    LspSignatureActiveParameter = { link = 'Visual' },
    Macro = { link = 'PreProc' },
    MatchParen = { fg = opts.accent, bg = opts.bg, bold = true },
    ModeMsg = { fg = opts.fg },
    MoreMsg = { fg = opts.fg },
    MsgArea = {},
    MsgSeparator = {},
    NonText = { fg = p.gray },
    Normal = { fg = opts.fg, bg = opts.bg },
    NormalFloat = { fg = opts.fg, bg = opts.popup_bg },
    NormalNC = {},
    Number = { link = 'Constant' },
    Operator = { fg = opts.fg },
    Pmenu = { fg = opts.fg, bg = opts.popup_bg },
    PmenuExtra = { link = 'Pmenu' },
    PmenuExtraSel = { link = 'PmenuSel' },
    PmenuKind = { link = 'Pmenu' },
    PmenuKindSel = { link = 'PmenuSel' },
    PmenuMatch = { fg = opts.accent, bold = true },
    PmenuMatchSel = { fg = opts.popup_sel_fg, bold = true },
    PmenuSbar = { bg = opts.popup_bg },
    PmenuSel = { fg = opts.popup_sel_fg, bg = opts.popup_sel_bg, bold = true },
    PmenuThumb = { bg = opts.accent },
    PreCondit = { link = 'PreProc' },
    PreProc = { fg = opts.fg },
    Question = { fg = opts.fg },
    QuickFixLine = { bg = opts.cursorline_bg },
    Repeat = { link = 'Statement' },
    Search = { fg = opts.selection_fg, bg = opts.selection_bg, bold = true },
    SignColumn = { fg = opts.fg, bg = opts.bg },
    SnippetTabstop = { link = 'Visual' },
    Special = { fg = opts.accent },
    SpecialChar = { link = 'Special' },
    SpecialComment = { link = 'Special' },
    SpecialKey = { fg = p.gray },
    SpellBad = { sp = p.fl_red, undercurl = true },
    SpellCap = { sp = p.fl_cyan, undercurl = true },
    SpellLocal = { sp = p.green, undercurl = true },
    SpellRare = { sp = p.fl_magenta, undercurl = true },
    Statement = { fg = opts.fg, bold = true },
    StatusLine = { fg = opts.bg, bg = opts.fg },
    StatusLineNC = { fg = opts.fg, bg = opts.cursorline_bg },
    StatusLineTerm = { link = 'StatusLine' },
    StatusLineTermNC = { link = 'StatusLineNC' },
    StorageClass = { link = 'Type' },
    String = { fg = opts.fg },
    Structure = { link = 'Type' },
    Substitute = { fg = opts.selection_fg, bg = opts.selection_bg },
    TabLine = { fg = opts.fg, bg = opts.cursorline_bg },
    TabLineFill = { bg = opts.bg },
    TabLineSel = { fg = opts.bg, bg = opts.fg },
    Tag = { link = 'Special' },
    TermCursor = { fg = opts.bg, bg = opts.caret },
    TermCursorNC = { fg = opts.bg, bg = p.gray },
    Title = { fg = opts.fg, bold = true },
    Todo = { fg = opts.accent, bold = true },
    Type = { fg = opts.fg },
    Typedef = { link = 'Type' },
    Underlined = { underline = true },
    VertSplit = { fg = p.gray },
    Visual = { fg = opts.selection_fg, bg = opts.selection_bg },
    WarningMsg = { fg = p.fl_orange },
    Whitespace = { link = 'NonText' },
    WildMenu = { fg = opts.popup_sel_fg, bg = opts.popup_sel_bg, bold = true },
    WinSeparator = { fg = p.gray },
    diffAdded = { link = 'DiffAdd' },
    diffRemoved = { link = 'DiffDelete' },
    gitcommitOverflow = { link = 'WarningMsg' },

    -- mini.nvim
    MiniCompletionActiveParameter = { link = 'LspSignatureActiveParameter' },
    MiniDepsChangeAdded = { link = 'Added' },
    MiniDepsChangeRemoved = { link = 'Removed' },
    MiniDepsHint = { link = 'DiagnosticHint' },
    MiniDepsInfo = { link = 'DiagnosticInfo' },
    MiniDepsMsgBreaking = { link = 'DiagnosticWarn' },
    MiniDepsPlaceholder = { link = 'Comment' },
    MiniDepsTitle = { link = 'Title' },
    MiniDepsTitleError = { link = 'DiffDelete' },
    MiniDepsTitleSame = { link = 'DiffText' },
    MiniDepsTitleUpdate = { link = 'DiffAdd' },
    MiniDiffOverAdd = { link = 'DiffAdd' },
    MiniDiffOverChange = { link = 'DiffText' },
    MiniDiffOverContext = { link = 'DiffChange' },
    MiniDiffOverDelete = { link = 'DiffDelete' },
    MiniDiffSignAdd = { fg = p.fl_green },
    MiniDiffSignChange = { fg = p.fl_cyan },
    MiniDiffSignDelete = { fg = p.fl_red },
    MiniFilesBorder = { link = 'FloatBorder' },
    MiniFilesBorderModified = { link = 'DiagnosticFloatingWarn' },
    MiniFilesCursorLine = { link = 'CursorLine' },
    MiniFilesDirectory = { link = 'Directory' },
    MiniFilesFile = {},
    MiniFilesNormal = { link = 'NormalFloat' },
    MiniFilesTitle = { link = 'FloatTitle' },
    MiniFilesTitleFocused = { link = 'FloatTitle' },
    MiniTrailspace = { bg = p.fl_red },
  }
end

-- Generate terminal colors for a theme
function M.make_terminal(opts)
  local p = M.palette
  return {
    [0] = p.black,
    [1] = p.fl_red,
    [2] = p.green,
    [3] = p.yellow,
    [4] = p.fl_blue,
    [5] = p.fl_magenta,
    [6] = p.fl_cyan,
    [7] = p.gray,
    [8] = p.gray,
    [9] = p.fl_red,
    [10] = p.fl_green,
    [11] = p.fl_yellow,
    [12] = p.fl_blue,
    [13] = p.fl_magenta,
    [14] = p.fl_cyan,
    [15] = p.white,
  }
end

return M
